theme: jekyll-theme-merlot
title: My Jekyll Blog
email: example@example.com
description: My latest stories and photos
url: https://mecharaspoutine.github.io
twitter_username: mecharaspoutine
github_username: mecharaspoutine
description: Ce blog est consacré au développement logiciel en général, et plus précisement jeux-video et intelligence artificielle.
